### PR TITLE
External table file

### PR DESCRIPTION
**Pull request by andreasscherbaum**
Add blog posting about file:// protocol in GPDB

### CODE REVIEW

**Comment by rvs** [comment]
Great blog post -- and very timely for the preliminary work I'm doing on PXF. My general comment is that it really should be part of an overall GPDB FAQ, rather than a blog post on Pivotal engineering blog (we can still blog pointing to the FAQ). What do you think?

My other suggestions related to content are (especially if we turn this into a real FAQ):
   * talk about how built-in implementation for external tables around URL-based files is different from all the other external table modules
   * talk about serialization/deserialization functions that can be plugged in via custom FORMAT clause
   * talk about what parts of GPDB actually call the functions that protocol plugins register

Makes sense?

**Comment by andreasscherbaum** [comment]
This blog post is very specifically just about the file:// protocol. There will be another one just about the gpfdist:// protocol, and then maybe a more general one.

The reason for going deep into the details of each protocol is that in the past several people raised questions about how each of the protocols work, and what is and is not possible with each of them.

> talk about serialization/deserialization functions that can be plugged in via custom FORMAT clause

Since that affects external tables in general, and not the file:// protocol itself, it's something which asks for yet another blog post. This one is already long enough.


> talk about how built-in implementation for external tables around URL-based files is different from all the other external table modules
> talk about what parts of GPDB actually call the functions that protocol plugins register

Can you elaborate on that? And how is that relevant to how it works for the end user (compared to, let's say a developer writing new plugins).

**Comment by rvs** [comment]
You didn't seem to answer my question on starting a permanent FAQ on the GPDB side. Can you please share your thoughts?

Now, take it from somebody who had to learn these things in the past couple of weeks -- talking about just file:// protocol without mentioning how it relates to all the other external table protocols will confuse the reader. Especially given our implementation where file:// is a special case. Now, I'm not saying you should co-mingle all the protocol in a single blog post, but I really think you should put things in context.

Also, it is fine if you're trying to draw a line at the users -- still it would be nice to have a place for a developer-centric FAQ (covering, for example, the implementation details I've suggested).

**Comment by andreasscherbaum** [comment]
> You didn't seem to answer my question on starting a permanent FAQ on the GPDB side. Can you please share your thoughts?

Yes, that's one way to do it. And once the engineering blog has enough technical content to fill in the FAQ, one can always link from the FAQ to the blog. Personally I would keep a FAQ more high-level, not very technical, and with fewer examples.

> still it would be nice to have a place for a developer-centric FAQ (covering, for example, the implementation details I've suggested)

Counter question: do you have a realistic target group for such a FAQ, or is it more a "would be nice to have" thing? Compared to the questions I've seen in the past, about how external tables work in general.
Who is going to implement more protocols in the near future? And will such a FAQ be enough to start with writing a new protocol, or is a discussion on the -dev mailinglist the better place? After all, a new protocol must be merged into the code, it's not something which works standalone.

**Comment by rvs** [comment]
To answer your question: I'd like to target contributors as much as users. But more selfishly, I'd love for this FAQ I'm proposing to exist two weeks ago -- it would've saved me quite a bit of time.

Whether or not that Q is really F -- dunno. Especially with a long term commitment to FDW as the interface choice for this functionality perhaps it isn't really that F -- but I guess if I'm the one preparing the FAQ I might as well use the power vested in me ;-)

**Pull request merged**
