### PR TITLE
New post: Setting up Kotlin with Android and tests

### PR DESCRIPTION
**Pull request by lkogler**

### CODE REVIEW

**Comment by lkogler** [comment]
@pivotal/engineering-directors This post is ready to go. Do I have to do anything else for it to be reviewed?

**Comment by tsaleh** [comment]
Thanks @lkogler!  This post is really crying out for some screenshots.  Do you think you could add some?

**Comment by lkogler** [comment]
I'm not really sure what a screenshot would add to this post.  The app doesn't do anything (it's just a hello world app), so screenshots of it would not be very interesting.  Is there something specific you would want to see?

**Comment by tsaleh** [comment]
@lkogler Thanks for making us rethink how we're running the blog.  I setup travis to auto-deploy anything on `master`, and gave everyone push rights.  I've merged this, but first set `draft: true` in the header so you could preview on staging and decide when you wanted to publish it.  See the README for all the details.  Happy blogging!

**Comment by tsaleh** [comment]
@lkogler for the screenshot, I was thinking something like what they have on the Kotlin website - https://kotlinlang.org/docs/tutorials/kotlin-android.html, but reading through the article, I can see that that might be pretty redundant.

**Pull request closed without merging**
