### PR TITLE
Improve OpenGraph tags and include structured data

### PR DESCRIPTION
**Pull request by textbook**
- Extract logo to SVG file for reference purposes
 - Add more Twitter-related OG tags
 - Add structured data JSON for Google etc.

### CODE REVIEW

**Comment by osis** [comment]
Thanks for the PR @textbook! To validate I'm pushing the app and using...

## https://cards-dev.twitter.com/validator

## **Before**
screen shot 2017-06-25 at 9 31 31 am

## **After**
screen shot 2017-06-25 at 9 30 52 am


## https://developers.facebook.com/tools/debug/sharing

## **Before**
screen shot 2017-06-25 at 9 08 57 am

## **After**
screen shot 2017-06-25 at 9 17 03 am

## http://opengraphcheck.com/

## **Before**
screen shot 2017-06-25 at 9 39 09 am

## **After**
screen shot 2017-06-25 at 9 11 16 am

## **And since you added structured data, https://search.google.com/structured-data/testing-tool**

## **Before**
screen shot 2017-06-25 at 9 34 02 am

## **After**
screen shot 2017-06-25 at 9 33 22 am

This is awesome! Are you worries about that error that Google is throwing about the Image URL?

**Comment by textbook** [comment]
@osis thanks for taking a look. According the [the schema.org docs](http://schema.org/BlogPosting) the image _can_ just be a URL, and [Google's docs](https://developers.google.com/search/docs/data-types/articles) say the image is only required for AMP pages. Not sure why it thinks the logo URL is invalid, though.

**Comment by osis** [comment]
@textbook Okay cool, seems to be a warning anyways. There is a logo URL error but I think that's due to my lazy cf push. Verifying...

screen shot 2017-06-25 at 10 26 33 am

**Comment by osis** [comment]
@textbook Oddly enough, I don't think Google likes the ImageObject for the logo?

https://developers.google.com/search/docs/data-types/logo

screen shot 2017-06-25 at 10 35 41 am

**Comment by textbook** [comment]
@osis that _is_ weird, because when I tried just putting the URL for the logo attribute I got _"http://engineering.pivotal.io/images/logo.svg (The attribute logo.itemtype has an invalid value.)"_ from the structured data testing tool.

**Comment by osis** [comment]
@textbook Also confused since [this page](https://developers.google.com/search/docs/data-types/articles) has an example of a logo that's an ImageObject. Also found this...

https://webmasters.stackexchange.com/questions/90233/why-is-my-itemprop-image-markup-incorrect

**Comment by osis** [comment]
Ah I see, it doesn't like the fact that it's an SVG.

screen shot 2017-06-25 at 10 51 43 am

**Comment by textbook** [comment]
Ah, yes, that must be it; per https://developers.google.com/search/docs/data-types/articles, *"Images should be in .jpg, .png, or. gif format"* (as an `ImageObject`). I'll re-inline the SVG to the main page and add a small PNG version of the logo to keep Google happy.

**Comment by osis** [comment]
Looks good! Let's merge and see how Google/others digests. Thanks @textbook!

**Pull request merged**
