### PR TITLE
Add a page per author

### PR DESCRIPTION
**Pull request by andreasscherbaum**
Modify all author links to point to the author page
Add basic profile information (Twitter, GitHub, Blog) on the author page

### CODE REVIEW

**Comment by ascherbaum-pivotal** [comment]
@tsaleh @ihuston Can you please look at this?

I added author pages for every author. Every author in posts, in the main page and in category pages links to the author page (instead of Twitter, or nothing if Twitter is not provided).

The author page provides name, Twitter link(s) (if multiple), Blog links (new) and links to GitHub profiles, as well as a list of blog posts where the author participated.

**Comment by ascherbaum-pivotal** [comment]
@tsaleh @ihuston I plan to push this later this week.

**Comment by osis** [comment]
@ascherbaum-pivotal I'll take a look at this today.

**Comment by osis** [comment]
@ascherbaum-pivotal This is great! Thanks for doing this. How do you feel about moving that section in the middle and putting the social icons in the header to bring the articles closer to the top?

**Comment by andreasscherbaum** [comment]
@osis: That's actually not easy to do - the header is generated in a separate file, and you have to push and scratch around all the data which you want to display there :-( One of the problems of using a static template engine.

Was also thinking about making the social items just icons with links, instead of names with links. But then again, who will recognize you by a simple Twitter icon, instead of your Twitter username?

The entire block with the name and social data could need some design love, but I'm definitely not the guy who can do that. If you can do it, you can either add it to my PR, or I commit it and you can follow up with another PR.

**Comment by osis** [comment]
@ascherbaum-pivotal Thanks for the context. The designer here is excited to take a look to see what we can do. In the interest of being agile, lets merge this and I'll ping you on future PRs that adjust the layout of this page in the future.

**Pull request merged**
