### PR TITLE
Added qemu-img line for vmware vsphere

### PR DESCRIPTION
**Pull request by keremavci**

### CODE REVIEW

**Comment by osis** [comment]
@cunnie what do you think?

**Comment by cunnie** [comment]
👍

It has been something I've been meaning to document for a while (the vSphere options). Thanks @keremavci , and thanks @osis for bringing this to my attention (I don't know how you're able to stay on top of all the things you do).

**Comment by cunnie** [comment]
Thanks again, @osis — I'll browse the blog repo periodically and see if there are any PRs for either my posts or someone else's, and if it's for someone else I'll reach out to them like you did to me.

(p.s. I thought I had merged it but obviously hadn't — thanks for catching it!)

**Comment by cunnie** [comment]
Thanks again, @osis — I'll browse the blog repo periodically and see if there are any PRs for either my posts or someone else's, and if it's for someone else I'll reach out to them like you did to me.

(p.s. I thought I had merged it but obviously hadn't — thanks for catching it!)

**Pull request merged**
