### PR TITLE
Add blog post to advocate for git switch and restore over git checkout

### PR DESCRIPTION
**Pull request by rctay**

### CODE REVIEW

**Comment by rctay** [comment]
Thanks for having a look @davebarnes97, I've made some edits based on your comments. Apparently there is a cool Github Actions pipeline going on for pull requests that pushes to `https://pivotal-cf-blog-staging.cfapps.io/<pr number>` which I noticed after looking at the build log - you can view the rendered posts (with images!) here: https://pivotal-cf-blog-staging.cfapps.io/270/post/better-specificity-with-git-switch-and-restore/

**Comment by davebarnes97** [comment]
> you can view the rendered posts (with images!) here: https://pivotal-cf-blog-staging.cfapps.io/270/post/better-specificity-with-git-switch-and-restore/
Permissions issue, maybe? I just get a 404 Not Found when I follow that link.

**Comment by rctay** [comment]
I changed the title so that's why that link didn't work, try this one:  https://pivotal-cf-blog-staging.cfapps.io/270/post/git-switch-restore-improved-user-experience/

> > you can view the rendered posts (with images!) here: https://pivotal-cf-blog-staging.cfapps.io/270/post/better-specificity-with-git-switch-and-restore/
> > Permissions issue, maybe? I just get a 404 Not Found when I follow that link.

**Comment by rctay** [comment]
Closing as I posted on the Tanzu Developer blog instead, check it out! https://tanzu.vmware.com/developer/blog/git-switch-and-restore-an-improved-user-experience/

**Pull request closed without merging**
