### PR TITLE
Add a blog on Agile/TDD for program logic people.

### PR DESCRIPTION
**Pull request by totherme**

### CODE REVIEW

**Comment by tsaleh** [comment]
> Academic computer scientists - quite rightly - tend to focus on (2). There are good reasons for this - success in (2) is relatively easy to measure, even if you're developing a small prototype in isolation from the market it's ultimately aimed at. On the other hand, I think Agile/TDD (Test Driven Development) is really good at (1). When I was living in academia I often found myself arguing that formal methods and proof-based techniques were better at (2) than TDD can ever be2. This might be true3, but it misses the point. The point is that it doesn't matter how good an engineer is at (2) if they have no plan for (1). For the rest of this post, I'm going to explore the strategy we use at Pivotal for (1) and what that might mean for academic toolsmiths who want us to use their methods and tools when we come to do (2). Many of the things I mention here will also turn out to be quite handy for (3) as well, but to do that justice will require another post.

I think this would read better if you found a way of not using "(1)" and "(2)" repeatedly.  Maybe give each of those methods pithy names?

**Comment by tsaleh** [comment]
> Yes, thanks -- I think it's safe to assume the client wanted a broadcast message, not just a message to some random client.". So, once the tests are all green, our engineers are free to write a new test for this new, inferred part of the spec (meanwhile, the PM might update the acceptance criteria to repeat the informal test with two clients). The tests for this story now look like this...

I might be being pedantic here, but I'd argue that the story was done as specified, and that the PM should create new stories for the extra behavior.  Would this change the post's narrative?

**Comment by tsaleh** [comment]
I think the post could be visually improved by breaking it up with subheaders.  An image or two would also be great, but I can't think of a relevant image to add.

**Comment by tsaleh** [comment]
@totherme had a chance to incorporate any of these items?

**Comment by Osis** [comment]
Good on mobile. Guess we're waiting on images though?

**Comment by totherme** [comment]
Done -- thanks! :)

**Comment by tsaleh** [comment]
We've changed how we're managing this whole shebang#! (see what I did there?)

I've merged this draft post, which automatically published it [here](http://pivotal-cf-blog-staging.cfapps.io/), and we've granded all pivots push rights to this repo.  If you're happy with the post, then remove the `draft: true` line from the header.  [Here are some quick tips for writing good posts](https://github.com/pivotal/blog#writing-a-good-post) (which I also encourage you to contribute to).

Happy blogging!

**Pull request merged**
