### PR TITLE
Edits to blog post

### PR DESCRIPTION
**Pull request by marie-cd**
Overall this is an awesome post! I made a few edits for readability. Are there any other areas for improvement aside from looking for a better way for multiple team members to join an ad-hoc video call?

Also, I use a lot of exclamation points when I write. Please, please feel free to tone it the heck down!

### CODE REVIEW

**Comment by tsaleh** [comment]
Hey @marie-cd - Looks like the travis build failed.  Can you investigate?

Other than that, we actually encouraging a sort of [publishing anarchy](https://github.com/pivotal/blog/blob/master/README.md).  You should push this to `master` as a draft, then solicit feedback from people via the staging site, and set it to published whenever you think it's ready.

**Comment by mcwumbly** [comment]
would a PR be a good way to suggest edits to a post that has already been published?

**Comment by bsnchan** [comment]
Sorry @tsaleh, I asked my team for to read my blog post draft and to provide feedback. @marie-cd suggested her edits to my blog post through a PR.

Maybe we can think of a better way to obtain feedback from team members if a PR is not the correct way to do it.

**Comment by bsnchan** [comment]
Looks like YAML just doesn't like the title because the title was not wrapped in quotes. I added in the edits and title-fix in this commit: https://github.com/pivotal/blog/commit/75254f98b3aabec70a6a27397aabcba9797fc5df

Thanks @marie-cd for the suggestions!

**Comment by tsaleh** [comment]
Ah, that makes sense - sorry about the confusion :)  I think a PR is fine,
but maybe we should sort-of address the PR to the original author via an @
mention, just to make it clear who it's for.

**Pull request closed without merging**
