### PR TITLE
Remove doubled site title in header

### PR DESCRIPTION
**Pull request by andreasscherbaum**

### CODE REVIEW

**Comment by tsaleh** [comment]
:+1:

**Comment by nertzy** [comment]
Does this eliminate the site title from the `<title>` on article pages?

**Comment by andreasscherbaum** [comment]
No. It just leaves one of them. Right now it's:

site title - site title

Which does not make sense.

**Comment by ascherbaum-pivotal** [comment]
I'm going to merge this tomorrow, if no one objects.

**Comment by tsaleh** [comment]
:+1:

**Pull request merged**
