### PR TITLE
Blog on Firehose Plugin for the CF CLI

### PR DESCRIPTION
**Pull request by wfernandes**

### CODE REVIEW

**Comment by tsaleh** [comment]
Thanks @wfernandes -- I love the post!

I hope you don't mind some grammatical and stylistic nitpicks...

Is... | May be better as... 
---- | -----
You know that saying 'With great power come great bragging rights | You know **the** saying 'With great power **comes** great bragging rights 
How can I have admin access? | How can I obtain admin access?
But in case you do not want to have user interaction, then you can use the --filter flag provided. | You can also use the `--filter` flag to have the plugin operate without user interaction.
If you want it all, `cf nozzle --no-filter`. | If you want all logs and not automatically enter interactive mode, you can pass in the `--no-filter` flag.

And I'd suggest capping the post off with a quick paragraph, maybe offering suggestions on how this could be used in a production environment -- for debugging, or for building on top of PCF.

Finally, is this great feature in our docs, @kimahoff?

**Comment by wfernandes** [comment]
Hey Tammer,

Thanks. I appreciate the feedback and I'll make the changes.

Warren

**Comment by kimahoff** [comment]
Thanks @tsaleh, we have some info (mainly here http://docs.pivotal.io/pivotalcf/loggregator/cli-plugin.html) but this has some additional material.

**Comment by wfernandes** [comment]
@tsaleh updated with recommended feedback.

**Comment by wfernandes** [comment]
Any news when this post will show up on the live site?

**Comment by tsaleh** [comment]
Sorry about that, @wfernandes - this post somehow got added and then removed:

```
$ g log --follow -- content/post/Firehose-Plugin.md
commit 7807e088f2460b914d2847aa07a18f5b2462c65a
Author: Warren Fernandes <warren.f.fernandes@gmail.com>
Date:   Tue Oct 27 09:20:00 2015 -0600

    Removing the actual post from this branch

commit 3a830722caad023c0251fb652cf4d09154eba310
Author: Warren Fernandes <warren.f.fernandes@gmail.com>
Date:   Mon Oct 26 13:10:22 2015 -0600

    Updated with recommended feedback

commit 210d552097fece22eeda75777c5aa6630cf10ad7
Author: Warren Fernandes <warren.f.fernandes@gmail.com>
Date:   Tue Oct 20 21:28:15 2015 -0600

    Blog on Firehose Plugin for the CF CLI
```

I'll try to resurrect it today.

**Comment by tsaleh** [comment]
@wfernandes Quick update - I'd like to add a diagram to the top of the post, but [I'm waiting on the Loggregator team to give me the Graffle source](https://cloudfoundry.slack.com/archives/loggregator/p1447063287000005).

**Comment by wfernandes** [comment]
I can do that when I get in work today. Was there something specific you
needed?

**Comment by tsaleh** [comment]
Sure - I just need to export a larger version of that diagram, so we can use it in the post.  Something full-width, without the border, and maybe transparent background.

**Comment by tsaleh** [comment]
@Osis can you take a look at this article on mobile?  I added a `max-width: 100%;` to all `figure img` tags, which I think makes it work there.

**Comment by Osis** [comment]
@tsaleh Article looks good. I think there is a general table formatting weirdness that can be fixed at the Pivotal UI level.

**Pull request merged**
