### PR TITLE
Draft post on Vim

### PR DESCRIPTION
**Pull request by Petahhh**
Signed-off-by: Peter Tran <ptran@pivotal.io>

### CODE REVIEW

**Comment by osis** [comment]
Haha so many gifs. Amazing!

**Comment by osis** [comment]
Going through the content take a good bit of scrolling. Have you explored use the ```left``` and ```right``` styles to get more of a two column format?

**Comment by osis** [comment]
Format suggestions:
1. Put movement first
1. Put "Insert Mode" before "Text Manipulation" since those put you into insert mode anyways

**Comment by Petahhh** [comment]
@osis I moved the sections around as you suggested. I also experimenting with using tables in the movement section. I created two columns and alternated the gifs from the left to right side. I thought it gave it a better visual break. Let me know if you think it's okay and I'll apply it to the rest of the post. (Vim macros to the rescue!)

**Comment by osis** [comment]
I'm personally a fan of keeping content in the same column for readability, but that's up to you. Like what you did with the tables! Feel free to play with the format as well. Maybe explain the movie HJKL and put all four GIFs in a grid below?

**Comment by Petahhh** [comment]
@osis Updated and squashed the commits. Let me know if it's okay and I'll publish it and update the date

**Comment by osis** [comment]
I would double-check header sizes for consistency and maybe check out the [Pivotal UI Typography](https://styleguide.pivotal.io/static/versions/2/css_base_typography.html#type_colors) page to see how your instructions can "pop".

Seems fine though. Always feel free to publish; you can always adjust after if you'd like.

**Comment by Petahhh** [comment]
@osis I've updated the PR to officially publish the post and updated the date. Could you please accept it? I see that I don't have write permissions yet.

**Pull request merged**
