### PR TITLE
First post

### PR DESCRIPTION
**Pull request by tsaleh**
@pivotal/pivotal-engineering-directors can I get some eyes on this post before merging?

### CODE REVIEW

**Comment by tsaleh** [comment]
Screenshot: 

a team sport pivotal engineering journal 2015-10-02 12 pm-15-19

**Comment by flavorjones** [comment]
LGTM, let's :shipit:

**Comment by tsaleh** [comment]
@onsi thinks I mention Consul, and wants to change the last line to "Transform how the world builds software”

**Comment by tsaleh** [comment]
Fixed the Consul typo - meant Concourse.

**Pull request merged**
