### PR TITLE
jasmine blog post

### PR DESCRIPTION
**Pull request by slackersoft**
Blog post to talk about jasmine and how we're moving forward with support for older versions of jasmine @pivotal/pivotal-engineering-directors

### CODE REVIEW

**Comment by tsaleh** [comment]
Thanks @slackersoft!  Is this in progress, or finished?  Can you get another jasmine person to +1 it (or are you the only one? o_O)?

**Comment by slackersoft** [comment]
It's short, but I think it pretty much sums everything up.

@infews @ragaskar @gerg Thoughts?

**Comment by ragaskar** [comment]
Content-wise, seems fine. Maybe a little odd for the engineering blog, it's more like a tidbit of news around Jasmine -- I would expect to see something like this on the jasmine-js mailing list or on the Jasmine wiki. I guess it really depends on what sort of content we expect to see on the eng blog.

**Comment by slackersoft** [comment]
I wanted it to be somewhere more permalinkable than the jasmine-js google group, but more time related than the wiki. Since we've posted other types of jasmine updates (2.0 release etc.) to previous blogs, this seemed like the right kind of place for it.

But as @ragaskar said, it depends what kind of content we want on the engineering blog.

**Comment by tsaleh** [comment]
We've changed how we're managing this whole shebang#! (see what I did there?)

I've merged this draft post, which automatically published it [here](http://pivotal-cf-blog-staging.cfapps.io/), and we've granded all pivots push rights to this repo.  If you're happy with the post, then remove the `draft: true` line from the header.  [Here are some quick tips for writing good posts](https://github.com/pivotal/blog#writing-a-good-post) (which I also encourage you to contribute to).

Happy blogging!

PS: you'll want to change to the new `authors:` format in the frontmatter before publishing.

**Pull request merged**
